namespace: zjpeterson
name: snowitsm
version: 1.1.0-dev1
readme: README.md
authors:
  - XLAB Steampunk <steampunk@xlab.si>
  - Abhijeet Kasurde <akasurde@redhat.com>
  - Zach Peterson <zpeterson@redhat.com>
description: Fork of Ansible Collection for interacting with ServiceNow ITSM
license_file: LICENSE
tags:
  - servicenow
repository: https://github.com/zjpeterson/servicenow.itsm/tree/galaxy
homepage: https://github.com/zjpeterson/servicenow.itsm/tree/galaxy
issues: https://github.com/zjpeterson/servicenow.itsm/tree/galaxy
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
